version: 2.1

commands:
  install-hclq:
    steps:
      # see https://github.com/mattolenik/hclq#auto-updating-script
      - run: |
          curl -sSLo install.sh https://install.hclq.sh
          chmod +x install.sh
          # needs an interactive session somehow
          env -i sh ./install.sh

jobs:
  hclq:
    docker:
      - image: cimg/go:1.18.2
    resource_class: medium
    steps:
      - checkout
      - install-hclq
      - run:
          name: HCLQ get
          command: |
            cat example.tf | hclq get 'data.foo.bar'
      - run:
          name: HCLQ set
          command: |
            cat example.tf | hclq set 'data.*.bar' "hogehoge" > modified.tf
            
            cat modified.tf

workflows:
  main:
    jobs:
      - hclq
